<a href="https://colab.research.google.com/github/vcbonani/Python/blob/main/Pandas_IO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [140]:
import pandas as pd

In [141]:
#Lendo arquivos CSV
url_csv = 'https://raw.githubusercontent.com/alura-cursos/Pandas/refs/heads/main/superstore_data.csv'
dados_mercado = pd.read_csv(url_csv, sep = ',') #gera um dataframe do arquivo csv
dados_mercado.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [142]:
url_csv_ponto_virgula = 'https://raw.githubusercontent.com/alura-cursos/Pandas/refs/heads/main/superstore_data_ponto_virgula.csv'
dados_mercado_2 = pd.read_csv(url_csv_ponto_virgula, sep = ';')
dados_mercado_2.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [143]:
#como detectar qual a codificação (enconding) de um arquivo
import chardet

with open('../dados/entrada/superstore_data.csv', 'rb') as file:
    print(chardet.detect(file.read()))

{'encoding': 'ascii', 'confidence': 1.0, 'language': 'eo', 'mime_type': 'text/plain'}

In [144]:
#nrows -> determina quantas linhas eu quero do arquivo
dados_primeiras_linhas = pd.read_csv(url_csv, nrows = 10)
dados_primeiras_linhas

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
5,7348,1958,PhD,Single,71691,0,0,3/17/2014,0,336,...,240,32,43,1,4,7,5,2,1,0
6,4073,1954,2n Cycle,Married,63564,0,0,1/29/2014,0,769,...,15,34,65,1,10,10,7,6,1,0
7,1991,1967,Graduation,Together,44931,0,1,1/18/2014,0,78,...,0,0,7,1,2,1,3,5,0,0
8,4047,1954,PhD,Married,65324,0,1,11/1/2014,0,384,...,21,32,5,3,6,2,9,4,0,0
9,9477,1954,PhD,Married,65324,0,1,11/1/2014,0,384,...,21,32,5,3,6,2,9,4,0,0

In [145]:
#usecols -> selecione somente as colunas que o usuário informar com o nome da coluna ou o número da posição da coluna
dados_selecao = pd.read_csv(url_csv, usecols = ['Id', 'Year_Birth', 'Income'])
dados_selecao = pd.read_csv(url_csv, usecols = [0, 1, 4])
dados_selecao

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [146]:
#exporta o dataframe para um csv
#o parâmetro index não cria um novo índice
dados_selecao.to_csv('../dados/saida/dados_mercado_selecao.csv', index = False)

In [147]:
#lendo o csv exportado
dados_exportados = pd.read_csv('../dados/saida/dados_mercado_selecao.csv')
dados_exportados

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [148]:
#Desafio: lendo dados com vários parâmetros

url_dados_sus = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv'

#separados é ponto e vírgula, encoding é ISO-8859-1, o header é a partir da 4ª linha, o skipfooter desconsidera as últimas 9 linhas
dados_sus = pd.read_csv(url_dados_sus, sep = ';', encoding = 'ISO-8859-1', header = 3, skipfooter = 9, engine = 'python')

dados_sus

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"
5,Amapá,"1120973,34","1268740,33","974651,24","1141137,32","866346,18","1440978,95","1426659,48","1475551,38","1651341,43",...,"3253399,45","2946398,44","2416019,23","2203732,04","2218532,26","2566919,60","2802886,34","2817849,31","3188210,98","309860092,59"
6,Tocantins,"3441592,69","4985688,85","6205612,60","4984482,09","5511002,46","4927934,22","5445602,28","5413710,38","5596669,50",...,"9155572,36","8390267,72","8729632,49","7770885,66","527840,46","675277,05","419553,49","319160,87","1357751,33","1020028272,64"
7,Maranhão,"10723506,39","13559679,41","13985142,36","14809416,46","14505727,38","14908091,32","15784899,40","15195312,89","14951277,75",...,"35473489,49","32219037,29","30077152,72","33200778,47","31942670,33","30783403,58","30738750,31","30924484,99","39663677,48","3871069498,04"
8,Piauí,"7985142,43","10079928,25","10298372,45","10775976,33","10398360,88","10528253,88","11040107,92","10549176,40","10899198,97",...,"19908573,27","25663537,49","20230782,72","22389215,72","18911604,50","20883972,79","22689390,32","19400269,01","20018325,75","2280888802,74"
9,Ceará,"15539821,90","25735101,55","28724625,75","30676457,06","30604453,47","31272395,18","30925391,36","27851438,72","30362719,90",...,"56019506,33","61719491,69","56625919,77","59074596,33","56916499,66","50849353,22","52078218,88","53171253,41","62079618,54","6591836650,18"
10,Rio Grande do Norte,"5947814,08","9509755,83","10352238,59","10855108,50","11160168,19","10475071,38","11386349,96","10640817,47","11336030,28",...,"26337808,77","27579658,62","27721340,38","26048003,33","24737052,09","23846816,35","28044464,51","26317613,74","23306498,68","2660122027,15"
11,Paraíba,"10723002,45","11386274,47","12053643,87","12653528,76","12215107,11","12256928,49","12755413,77","12872578,37","12558296,11",...,"27294311,05","23288213,79","19480481,07","19988426,94","18418075,59","18099514,43","19524543,63","21302722,77","25750897,89","2614919044,63"
12,Pernambuco,"14393949,89","24181400,95","29991302,71","34806197,97","32147987,35","32239094,89","32685640,76","35457038,66","33668261,46",...,"74914677,43","77232881,01","71715677,42","66555628,25","78904176,21","70978052,15","83846222,44","75562664,69","83870992,73","8581189975,91"
13,Alagoas,"6243726,32","8376622,16","8408336,22","9090794,82","9338771,45","10068210,08","9887061,61","9373432,00","9563580,50",...,"18453860,49","19995280,39","18185986,17","18871513,02","18597375,56","17805273,37","17543184,88","18526929,38","22118639,05","2236415402,51"
14,Sergipe,"2780750,11","3676483,16","5051473,61","5046063,36","4741151,56","5401259,63","5521904,44","5238398,50","5187912,19",...,"10313262,56","11404646,48","10741986,60","12278300,58","12264609,05","11454427,82","12060864,70","13003816,54","13321494,41","1215853015,00"
15,Bahia,"21211522,47","28189304,95","34181483,52","39026934,13","42949566,82","47025972,04","47481695,17","46931248,28","44883379,31",...,"84204991,86","83478081,57","80540324,01","81250834,02","86257814,00","85871122,17","79961693,17","81992571,15","98746333,07","9791541570,52"
16,Minas Gerais,"45671659,76","70194037,10","79231336,95","77136537,58","80554440,63","94758522,83","85360064,11","84722528,10","84601757,95",...,"165759955,94","171048093,95","175439696,53","178279152,74","175253226,91","172509435,62","174722161,98","177270694,34","200471045,07","20418737536,66"
17,Espírito Santo,"5456723,98","9102212,86","10249595,97","11253833,56","10198619,17","13364258,29","13035374,08","12588595,77","12727433,30",...,"33474963,98","32364742,01","38569356,14","35748380,19","32030401,25","33674687,78","39642483,39","40243896,20","45490499,45","3405850698,58"
18,Rio de Janeiro,"23025258,52","28394310,93","44567062,94","44054604,82","44911021,15","48056212,24","49872379,35","50912706,60","49270352,76",...,"99331352,01","96339615,99","88305239,94","86995649,35","86776500,97","90416725,95","94179674,42","85583557,95","106837295,81","10337391164,52"
19,São Paulo,"91678473,48","148677526,82","156087269,23","161227125,43","187119397,64","187291126,07","194398399,48","184854516,35","188636359,55",...,"367648996,72","349900969,68","354117254,42","345733068,79","335084865,66","330489045,98","355149525,60","348827130,99","392946147,42","41396604304,13"
20,Paraná,"38266347,46","55384670,52","53801318,85","52460306,69","54419620,71","57811688,48","58094241,83","56982774,90","57549082,26",...,"109720663,59","129529222,48","122702263,26","129647873,97","126859051,02","120037066,76","122122779,12","132622112,72","140264608,52","14681514706,67"
21,Santa Catarina,"16504913,45","25651429,11","26743524,89","27181488,26","26845308,18","29909762,04","30789135,84","31250854,33","30019676,93",...,"61267297,89","65467585,93","71781494,82","69414431,71","68460616,55","70333079,37","71970474,56","74337524,03","81376630,57","7835011163,40"
22,Rio Grande do Sul,"30931325,46","57363420,01","51547794,07","56673338,49","48397733,07","52413429,62","56636376,98","56113054,70","55356224,30",...,"100579287,65","102609965,59","104401019,54","117458292,46","108853890,98","111760506,80","119992419,94","111797400,70","130155185,16","12764391179,92"
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"

In [149]:
## trabalhando com arquivo excel

url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

#obtém o nome das páginas(sheets) do excel
pd.ExcelFile(url).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [150]:
dados_co2 = pd.read_excel(url)

In [151]:
dados_co2

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,3.609674e+10,1.450697e+10,1.224263e+10,7.144928e+09,1.507923e+09,391992176.0,302294047.0,4749682.0
63100,Global,WLD,2018,3.682651e+10,1.474683e+10,1.226602e+10,7.529847e+09,1.569218e+09,412115746.0,302478706.0,4792753.0
63101,Global,WLD,2019,3.708256e+10,1.472598e+10,1.234565e+10,7.647528e+09,1.617507e+09,439253991.0,306638573.0,4775633.0
63102,Global,WLD,2020,3.526409e+10,1.417456e+10,1.119181e+10,7.556290e+09,1.637538e+09,407583673.0,296301685.0,4497423.0
63103,Global,WLD,2021,3.712385e+10,1.497960e+10,1.183716e+10,7.921829e+09,1.672592e+09,416525563.0,296145746.0,4693699.0

In [152]:
percapita = pd.read_excel(url, sheet_name = 'emissoes_percapita')

In [153]:
percapita.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
fontes = pd.read_excel(url, sheet_name = 'fontes')

In [155]:
fontes.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

In [156]:
#o parâmetro usecols permite selecionar algumas colunas do arquivo de origem
#no exemplo, são selecionadas as colunas de A a D
intervalo = pd.read_excel(url, sheet_name = 'emissoes_C02', usecols = 'A:D')

In [157]:
intervalo

              País ISO 3166-1 alpha-3   Ano         Total
0      Afeganistão                AFG  1750  0.000000e+00
1      Afeganistão                AFG  1751  0.000000e+00
2      Afeganistão                AFG  1752  0.000000e+00
3      Afeganistão                AFG  1753  0.000000e+00
4      Afeganistão                AFG  1754  0.000000e+00
...            ...                ...   ...           ...
63099       Global                WLD  2017  3.609674e+10
63100       Global                WLD  2018  3.682651e+10
63101       Global                WLD  2019  3.708256e+10
63102       Global                WLD  2020  3.526409e+10
63103       Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [158]:
#o parâmetro nrows obtém somente a quantidade de linhas especificadas, no exemplo são só 10
intervalo_2 = pd.read_excel(url, sheet_name='emissoes_C02', usecols = 'A:D', nrows=10)

In [159]:
intervalo_2.head()

          País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750      0
1  Afeganistão                AFG  1751      0
2  Afeganistão                AFG  1752      0
3  Afeganistão                AFG  1753      0
4  Afeganistão                AFG  1754      0

In [160]:
#exportando um dataframe para excel
percapita.to_excel('../dados/saida/co2_percapita.xlsx', index = False)

In [161]:
#essa é a url de uma planilha no drive                       entre o d/ e o /edit está o id da planilha que será usado
#                                                            |||||||||||||||||||||||||||||||||
url_planilha_drive = 'https://docs.google.com/spreadsheets/d/1e-dOLdElnztbUa7kUDre5k2PJfx4bLsu/edit?usp=sharing&ouid=110788630261722409853&rtpof=true&sd=true'

sheet_id = '1e-dOLdElnztbUa7kUDre5k2PJfx4bLsu'

#os parâmetros /gviz/tq usa uma api do google drive para acessar a planilha
#o parâmetro tqx=out:csv informa que ele será exportado como um arquivo csv
#o parâmetro sheet sem nada exportará a primeira aba do arquivo
url_drive = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

dados_co2_sheets = pd.read_csv(url_drive)

In [162]:
dados_co2_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [163]:
sheet_id = '1e-dOLdElnztbUa7kUDre5k2PJfx4bLsu'
sheet_name = 'emissoes_percapita'
#aqui, o parâmetro sheet traz a informação explícita de qual aba será exportada
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

percapita_sheets = pd.read_csv(url_percapita)

In [164]:
percapita_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [165]:
sheet_id = '1e-dOLdElnztbUa7kUDre5k2PJfx4bLsu'
sheet_name = 'fontes'
url_fontes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

fontes_sheets = pd.read_csv(url_fontes)

In [166]:
fontes_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

In [167]:
#Desafio: lendo dados de outro link

url_desafio_original = 'https://docs.google.com/spreadsheets/d/1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw/edit?gid=1214654498#gid=1214654498'

##pegar o id do arquivo do drive usando regex
import re

padrao = r"/d/([a-zA-Z0-9-_]+)/edit"
id_arquivo = re.search(padrao, url_desafio_original)
print(id_arquivo)

if id_arquivo:
  id_arquivo = id_arquivo.group(1)
  print(id_arquivo)
1
url_desafio = f'https://docs.google.com/spreadsheets/d/{id_arquivo}/gviz/tq?tqx=out:csv&sheet'

dados_desafio = pd.read_csv(url_desafio)
dados_desafio.head()

dados_desafio.to_csv('../dados/saida/emissoes_co2.csv', index = False)

<re.Match object; span=(36, 88), match='/d/1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw/e>
1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw

In [168]:
## MANIPULANDO ARQUIVOS JSON Javascript Object Notation

import pandas as pd

dados_pacientes = pd.read_json('../dados/entrada/pacientes.json')

In [169]:
dados_pacientes.head()

,ID_paciente,Doenca_cardiaca,IMC,Fumante,Consumo_alcool,AVC,Saude_fisica,Saude_mental,Dificuldade_caminhar,Sexo_biologico,Faixa_etaria,Raca,Diabetes,Atividade_fisica,Saude_geral,Horas_sono,Asma,Doenca_renal,Cancer_pele
0,0,Nao,16.60,Sim,Nao,Nao,3,30,Nao,Feminino,55-59,Branca,Sim,Sim,Muito boa,5,Sim,Nao,Sim
1,1,Nao,20.34,Nao,Nao,Sim,0,0,Nao,Feminino,80 ou +,Branca,Nao,Sim,Muito boa,7,Nao,Nao,Nao
2,2,Nao,26.58,Sim,Nao,Nao,20,30,Nao,Masculino,65-69,Branca,Sim,Sim,Razoavel,8,Sim,Nao,Nao
3,3,Nao,24.21,Nao,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,No,Boa,6,Nao,Nao,Sim
4,4,Nao,23.71,Nao,Nao,Nao,28,0,Sim,Feminino,40-44,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao

In [170]:
#este arquivo json não está normalizado, está aninhado
dados_pacients_2 = pd.read_json('../dados/entrada/pacientes_2.json')
dados_pacients_2

,Pesquisa,Ano,Pacientes
0,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi..."
1,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_..."
2,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi..."

In [171]:
#json_normalize normaliza os dados para um dataframe a partir da coluna especificada
df_normalizado = pd.json_normalize(dados_pacients_2['Pacientes'])
df_normalizado

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [172]:
#usando módulo JSON para importar arquivos json

import json

with open('../dados/entrada/pacientes_2.json') as f:
  dados = json.loads(f.read())

pd.json_normalize(dados, record_path='Pacientes')

,ID,Faixa_etaria,Sexo_biologico,RaÃ§a,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [173]:
#salvando um arquivo JSON

df_normalizado.to_json('../dados/saida/df_normalizado.json')

In [174]:
## IMPORTANDO UM JSON A PARTIR DE UMA API

import requests #a biblioteca requests contém as formas de obter o json de uma api
import json

#obtém o json
dados_usuarios = requests.get('https://jsonplaceholder.typicode.com/users')

#json.loads lê o json obtido
resultado = json.loads(dados_usuarios.text)

#visualizando como um dataframe o json
pd.DataFrame(resultado)

#normalizando o json
df_normalizado = pd.json_normalize(resultado)
df_normalizado

,id,name,username,email,phone,website,address.street,address.suite,address.city,address.zipcode,address.geo.lat,address.geo.lng,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models

In [175]:
##Lendo páginas web
import pandas as pd

In [176]:
dados_html = pd.read_html('../dados/entrada/filmes_wikipedia.html')
#o read_html busca as tags tables dentro da página web

dados_html

[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                             Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles
 1                     Casablanca          1942        Michael Curtiz
 2                  The Godfather          1972  Francis Ford Coppola
 3             Gone with the Wind          1939        Victor Fleming
 4             Lawrence of Arabia          1962            David Lean
 ..                           ...           ...                   ...
 95                 The Searchers          1956             John Ford
 96              Bringing Up Baby          1938          Howard Hawks
 97                    Unforgiven          1992        Clint Eastwood
 98  Guess Who's Coming to Dinner          1967        Stanley Kramer
 99           Yankee Doodle Dandy          1942        Michael Curtiz

                       Production companies  Rank
 0                       RKO Radio Pictures     1
 1                    Warner Bros. Pictures     2
 2   Paramount Pictures, Alfran Productions     3
 3          Selznick International Pictures     4
 4                         Horizon Pictures     5
 ..                                     ...   ...
 95                  C. V. Whitney Pictures    96
 96                      RKO Radio Pictures    97
 97                     The Malpaso Company    98
 98                       Columbia Pictures    99
 99                   Warner Bros. Pictures   100

 [100 rows x 5 columns],
           hidevteAFI's 100 Years...100 Movies (1998)  \
 0  Citizen Kane (1941) Casablanca (1942) The Godf...

         hidevteAFI's 100 Years...100 Movies (1998).1
 0  Citizen Kane (1941) Casablanca (1942) The Godf...  ]

In [177]:
type(dados_html) #confirmando que é uma lista
len(dados_html) #confirmando que contém 3 tabelas

3

In [178]:
top_filmes = dados_html[1] #passa a tabela desejada para uma variável

top_filmes

,Film,Release year,Director,Production companies,Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5
...,...,...,...,...,...
95,The Searchers,1956,John Ford,C. V. Whitney Pictures,96
96,Bringing Up Baby,1938,Howard Hawks,RKO Radio Pictures,97
97,Unforgiven,1992,Clint Eastwood,The Malpaso Company,98
98,Guess Who's Coming to Dinner,1967,Stanley Kramer,Columbia Pictures,99
99,Yankee Doodle Dandy,1942,Michael Curtiz,Warner Bros. Pictures,100

In [179]:
#escrevendo um arquivo html a partir de uma variável
top_filmes.to_html('../dados/saida/top_filmes.html')

In [180]:
#salvando em csv
top_filmes.to_csv('../dados/saida/top_filmes.csv', index = False)

In [181]:
#Lendo e escrevendo arquivos XML

dados_imdb = pd.read_xml('../dados/entrada/imdb_top_1000.xml')
dados_imdb

,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [182]:
#selecionando somente algumas colunas do dataframe
dados_imdb = dados_imdb.iloc[:, 2:10]
dados_imdb

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0
...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0
996,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0
997,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0
998,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0
999,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0

In [183]:
#exportando o dataframe para um xml
dados_imdb.to_xml('../dados/saida/filmes_imdb.xml', index = False)

In [184]:
#Desafio: lendo uma tabela de uma página web

dados_populacao = pd.read_html('../dados/entrada/Lista de países por população.html')

#conferindo os dados importados
dados_populacao

[     Unnamed: 0 Posição                    País (ou território dependente)  \
 0           NaN       1                                              Índia
 1           NaN       2                                      China[nota 1]
 2           NaN       3                                     Estados Unidos
 3           NaN       4                                          Indonésia
 4           NaN       5                                          Paquistão
 ..          ...     ...                                                ...
 245         NaN       –                     Ilha de Ascensão (Reino Unido)
 246         NaN     195                                           Vaticano
 247         NaN       –  [[File:|22x20px|border |alt=|link=]] Ilhas Coc...
 248         NaN       –                     Tristão da Cunha (Reino Unido)
 249         NaN       –                       Ilhas Pitcairn (Reino Unido)

     Estimativa da ONU Crescimento desde a última estimativa  \
 0       1 417 492 000                           -12 692 000
 1       1 407 934 000                            -1 390 000
 2         342 181 000                            -2 084 000
 3         285 783 000                            +3 337 000
 4         256 204 000                            +6 567 000
 ..                ...                                   ...
 245             1 100                                   NaN
 246               879                                   NaN
 247               605                                   NaN
 248               264                                   NaN
 249                67                                   NaN

          Estimativa Oficial
 0        Estimativa oficial
 1             Censo oficial
 2             Censo oficial
 3        Estimativa oficial
 4        Estimativa oficial
 ..                      ...
 245  Estimativa oficial[10]
 246      Estimativa oficial
 247      Estimativa oficial
 248  Estimativa oficial[11]
 249      Estimativa oficial

 [250 rows x 6 columns],
 Empty DataFrame
 Columns: [[Expandir]vdeListas de países, [Expandir]vdeListas de países.1]
 Index: [],
             0                                                  1
 0     Consumo  Bebidas Cerveja Idade legal Cannabis Adultos C...
 1     Energia  Eletricidade Produção Renovável Gás natural Ex...
 2         PIB  Crescimento Real PIB Nominal per capita PIB po...
 3    Produção  Alumínio Antimônio Bauxita Bismuto Carvão Rese...
 4  Transporte  Aeroportos Automóveis per capita Produzidos He...]

In [185]:
#conferindo quantas tabelas existem
len(dados_populacao)

#selecionando a primeira tabela
dados_populacao = dados_populacao[0]

In [186]:
#desconsiderando a coluna unnamed, crescimento desde a última estimativa, estimativa oficial
dados_populacao = dados_populacao.iloc[:, 1:4]

In [187]:
#analisando os dados
pd.set_option('display.max_rows', None)
dados_populacao

,Posição,País (ou território dependente),Estimativa da ONU
0,1,Índia,1 417 492 000
1,2,China[nota 1],1 407 934 000
2,3,Estados Unidos,342 181 000
3,4,Indonésia,285 783 000
4,5,Paquistão,256 204 000
5,6,Nigéria,236 213 000
6,7,Brasil,214 244 000
7,8,Bangladesh,177 567 000
8,9,Rússia[nota 2],146 022 000
9,10,México,131 013 000
10,11,Etiópia,125 092 825
11,12,Japão,124 127 899
12,13,Filipinas,109 581 078
13,14,República Democrática do Congo,105 823 799
14,15,Egito,102 334 404
15,16,Vietname,97 338 579
16,17,Turquia,84 339 067
17,18,Irã,83 992 949
18,19,Alemanha,83 783 942
19,20,Tailândia,69 799 978
20,21,Reino Unido,69 505 718
21,22,França,65 273 511
22,23,Itália,60 461 826
23,24,Tanzânia,59 734 218
24,25,África do Sul,59 308 690
25,26,Myanmar,54 409 800
26,27,Quénia,53 771 296
27,28,Coreia do Sul,51 269 185
28,29,Colômbia,50 882 891
29,30,Espanha,46 754 778
30,31,Uganda,45 741 007
31,32,Argentina,45 195 774
32,33,Argélia,43 851 044
33,34,Sudão,43 849 260
34,35,Ucrânia,43 733 762
35,36,Iraque,40 222 493
36,37,Afeganistão,38 928 346
37,38,Polónia,37 846 611
38,39,Canadá,37 742 154
39,40,Marrocos,36 910 560
40,41,Angola,36 604 681
41,42,Arábia Saudita,34 112 871
42,43,Malásia,34 112 440
43,44,Uzbequistão,33 469 203
44,45,Peru,32 971 854
45,46,Moçambique,31 255 435
46,47,Gana,31 072 940
47,48,Iémen,29 825 968
48,49,Nepal,29 136 808
49,50,Venezuela,28 435 940
50,51,Madagascar,27 691 018
51,52,Camarões,26 545 864
52,53,Costa do Marfim,26 378 274
53,54,Coreia do Norte,25 778 816
54,55,Austrália,25 499 884
55,56,Níger,24 206 644
56,–,Taiwan,23 816 775
57,57,Sri Lanka,21 413 249
58,58,Burquina Fasso,20 903 273
59,59,Mali,20 250 833
60,60,Roménia,19 237 691
61,61,Malawi,19 129 952
62,62,Chile,19 116 201
63,63,Cazaquistão,18 776 707
64,64,Zâmbia,18 383 955
65,65,Guatemala,17 915 568
66,66,Equador,17 643 054
67,67,Síria,17 500 657
68,68,Países Baixos,17 134 872
69,69,Senegal,16 743 927
70,70,Camboja,16 718 965
71,71,Chade,16 425 864
72,72,Somália,15 893 222
73,73,Zimbabwe,14 862 924
74,74,Guiné,13 132 795
75,75,Ruanda,12 952 218
76,76,Benim,12 123 000
77,77,Burundi,11 890 784
78,78,Tunísia,11 818 619
79,79,Bolívia,11 673 021
80,80,Bélgica,11 589 623
81,81,Haiti,11 402 528
82,82,Cuba,11 326 616
83,83,Sudão do Sul,11 193 725
84,84,República Dominicana,10 847 910
85,85,Grécia,10 768 477
86,86,Chéquia,10 708 981
87,87,Portugal,10 467 366
88,88,Jordânia,10 203 134
89,89,Azerbaijão,10 139 177
90,90,Suécia,10 099 265
91,91,Honduras,9 904 607
92,92,Emirados Árabes Unidos,9 890 402
93,93,Hungria,9 660 351
94,94,Tajiquistão,9 537 645
95,95,Bielorrússia,9 449 323
96,96,Áustria,9 006 398
97,97,Papua-Nova Guiné,8 947 024
98,98,Israel,8 655 535
99,99,Suíça,8 654 622
100,100,Togo,8 278 724
101,101,Serra Leoa,7 976 983
102,–,Hong Kong (China),7 496 981
103,102,Laos,7 275 560
104,103,Bulgária,6 948 445
105,104,Sérvia,6 926 705
106,105,Líbia,6 871 292
107,106,Líbano,6 825 445
108,107,Nicarágua,6 624 554
109,108,Quirguistão,6 524 195
110,109,El Salvador,6 486 211
111,110,Paraguai,6 109 644
112,111,Turquemenistão,6 031 200
113,112,Singapura,5 850 342
114,113,Dinamarca,5 792 202
115,114,Finlândia,5 540 720
116,115,Congo,5 518 087
117,116,Eslováquia,5 459 642
118,117,Noruega,5 421 241
119,118,Omã,5 106 626
120,119,Palestina,5 101 414
121,120,Costa Rica,5 094 118
122,121,Libéria,5 057 681
123,122,Irlanda,4 937 786
124,123,República Centro-Africana,4 829 767
125,124,Nova Zelândia,4 822 233
126,125,Mauritânia,4 649 658
127,126,Panamá,4 314 897
128,127,Kuwait,4 270 571
129,128,Croácia,4 105 267
130,129,Geórgia,3 989 167
131,130,Eritreia,3 546 421
132,131,Uruguai,3 473 730
133,132,Bósnia e Herzegovina,3 280 819
134,133,Mongólia,3 278 290
135,134,Arménia,2 963 243
136,135,Jamaica,2 961 167
137,136,Catar,2 881 053
138,137,Albânia,2 877 797
139,–,Porto Rico (Estados Unidos),2 860 853
140,138,Lituânia,2 722 289
141,139,Moldávia,2 640 438
142,140,Namíbia,2 540 905
143,141,Gâmbia,2 416 668
144,142,Botswana,2 351 627
145,143,Gabão,2 225 734
146,144,Lesoto,2 142 249
147,145,Macedónia do Norte,2 083 374
148,146,Eslovénia,2 078 938
149,147,Guiné-Bissau,1 968 001
150,148,Letónia,1 886 198
151,–,Kosovo,1 795 666
152,149,Barém,1 701 575
153,150,Guiné Equatorial,1 402 985
154,151,Trindade e Tobago,1 399 488
155,152,Estónia,1 326 335
156,153,Timor-Leste,1 318 445
157,154,Maurícia,1 271 768
158,155,Eswatini,1 160 164
159,156,Djibouti,988 000
160,157,Chipre,900 432
161,158,Fiji,896 445
162,–,Reunião (França),895 312
163,159,Comores,869 601
164,160,Guiana,786 552
165,161,Butão,771 608
166,162,Ilhas Salomão,686 884
167,–,Macau (China),649 335
168,163,Montenegro,649 335
169,164,Luxemburgo,625 978
170,–,Saara Ocidental (Marrocos),597 341
171,165,Suriname,586 632
172,166,Cabo Verde,555 987
173,167,Maldivas,540 544
174,168,Malta,441 543
175,–,Transnístria (Moldávia),469 000
176,169,Brunei,437 479
177,–,Guadalupe (França),400 124
178,170,Belize,397 628
179,171,Bahamas,393 244
180,–,Martinica (França),375 265
181,–,República Turca de Chipre do Norte (Chipre),351 965
182,172,Islândia,341 243
183,173,Vanuatu,307 145
184,–,Guiana Francesa (França),298 682
185,174,Barbados,287 375
186,–,Nova Caledônia (França),285 498
187,–,Polinésia Francesa (França),280 908
188,–,Mayotte (França),272 815
189,–,Abecásia (Geórgia),245 424
190,175,São Tomé e Príncipe,219 159
191,176,Samoa,198 414
192,177,Santa Lúcia,183 627
193,–,Guam (Estados Unidos),168 775
194,–,Curaçau (Países Baixos),164 093
195,178,Quiribáti,119 449
196,179,Micronésia,114 419
197,180,Granada,110 000
198,–,Aruba (Países Baixos),106 537
199,181,Tonga,106 017
200,–,U.S. Ilhas Virgens (Estados Unidos),106 988
201,182,São Vicente e Granadinas,104 332
202,–,Jersey (Reino Unido),103 267
203,183,Seicheles,99 258
204,184,Antígua e Barbuda,93 219
205,–,Ilha de Man (Reino Unido),84 263
206,185,Andorra,79 034
207,186,Domínica,72 412
208,–,Ilhas Cayman (Reino Unido),68 136
209,–,Guernsey (Reino Unido),67 462
210,-,Bermudas (Reino Unido),63 867
211,–,Gronelândia (Dinamarca),56 653
212,–,Ossétia do Sul (Geórgia),53 532
213,–,Ilhas Faroe (Dinamarca),52 889
214,–,Marianas Setentrionais (Estados Unidos),49 481
215,187,São Cristóvão e Neves,47 606
216,–,Ilhas Turks e Caicos (Reino Unido),45 114
217,–,Samoa Americana (Estados Unidos),45 035
218,–,São Martinho (Países Baixos),42 876
219,188,Ilhas Marshall,42 050
220,189,Liechtenstein,39 039
221,190,Mónaco,36 686
222,191,San Marino,35 745
223,–,Gibraltar (Reino Unido),32 679
224,–,São Martinho (França),31 948
225,–,Ilhas Virgens Britânicas (Reino Unido),30 122
226,–,Bonaire (Países Baixos),20 104
227,192,Palau,18 024
228,–,Ilhas Cook,17 849
229,–,Wallis e Futuna (França),15 997
230,–,Anguila (Reino Unido),15 793
231,193,Nauru,12 511
232,194,Tuvalu,11 204
233,–,São Bartolomeu (França),9 139
234,–,Santa Helena (território) (Reino Unido),6 158
235,–,São Pedro e Miquelão (França),5 816
236,–,Montserrat (Reino Unido),5 087
237,–,Ilhas Malvinas (Reino Unido),3 978
238,–,Santo Eustáquio (Países Baixos),3 879
239,–,Território Britânico do Oceano Índico (Reino U...,3 000
240,–,Ilha Norfolk (Austrália),2 169
241,–,Ilha Christmas (Austrália),1 996
242,–,Saba (Países Baixos),1 933
243,–,Niue (Nova Zelândia),1 626
244,–,Tokelau (Nova Zelândia),1 411
245,–,Ilha de Ascensão (Reino Unido),1 100
246,195,Vaticano,879
247,–,[[File:|22x20px|border |alt=|link=]] Ilhas Coc...,605
248,–,Tristão da Cunha (Reino Unido),264
249,–,Ilhas Pitcairn (Reino Unido),67

In [188]:
pd.reset_option('display.max_rows')

#tratando os dados

#Substituindo os textos de [Nota 1], [Nota 2] e [[File:|22x20px|border |alt=|link=]] na coluna de País
dados_populacao.replace(r'\[+.*?\]+', '', regex=True, inplace=True)

#confirmando a aplicação da substituição
dados_populacao.head(10)

  Posição País (ou território dependente) Estimativa da ONU
0       1                           Índia     1 417 492 000
1       2                           China     1 407 934 000
2       3                  Estados Unidos       342 181 000
3       4                       Indonésia       285 783 000
4       5                       Paquistão       256 204 000
5       6                         Nigéria       236 213 000
6       7                          Brasil       214 244 000
7       8                      Bangladesh       177 567 000
8       9                          Rússia       146 022 000
9      10                          México       131 013 000

In [189]:
#conferindo o restante dos dados
dados_populacao.tail(10)

    Posição     País (ou território dependente) Estimativa da ONU
240       –            Ilha Norfolk (Austrália)             2 169
241       –          Ilha Christmas (Austrália)             1 996
242       –                Saba (Países Baixos)             1 933
243       –                Niue (Nova Zelândia)             1 626
244       –             Tokelau (Nova Zelândia)             1 411
245       –      Ilha de Ascensão (Reino Unido)             1 100
246     195                            Vaticano               879
247       –   Ilhas Cocos (Keeling) (Austrália)               605
248       –      Tristão da Cunha (Reino Unido)               264
249       –        Ilhas Pitcairn (Reino Unido)                67

In [190]:
#transformando a coluna Estimativa da ONU para número
dados_populacao['Estimativa da ONU'] = dados_populacao['Estimativa da ONU'].str.replace(' ','', regex = False).astype(int)

In [191]:
#conferindo o tipo da coluna
dados_populacao.dtypes

Posição                              str
País (ou território dependente)      str
Estimativa da ONU                  int64
dtype: object

In [192]:
##Trabalhando com banco de dados

import sqlalchemy

In [193]:
'''fazendo importações do sqlalchemy
create_engine - motor para conexão com banco de dados
MetaData - classe que representa os metadados do BD
Table - representa uma tabela em um BD
inspect - permite inspecionar a estrutura do BD
'''
from sqlalchemy import create_engine, MetaData, Table, inspect

In [194]:
#criando um banco de dados do tipo sqlite, armazenar o banco na memória local
engine = create_engine('sqlite:///:memory:')

In [195]:
#base de dados csv

url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [196]:
import pandas as pd

In [197]:
dados = pd.read_csv(url)

In [198]:
dados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [199]:
#transformar um dataframe para banco de dados

#é passado o dataframe, qual o motor(engine) e a não-criação automática de índice
dados.to_sql('clientes', engine, index = False)

438463

In [200]:
#inspecionando o que existe no banco de dados
inspetor = inspect(engine)

#confirmando as tabelas criadas
print(inspetor.get_table_names())

['clientes']

In [201]:
#criando uma consulta no banco de dados
query = 'select * from clientes where Categoria_de_renda = "Empregado"'

In [202]:
#lendo o banco de dados
empregados = pd.read_sql(query, engine)

empregados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio

In [203]:
#Transformando o dataframe em uma tabela no engine
empregados.to_sql('empregados', con = engine, index = False)

226059

In [204]:
inspetor = inspect(engine)
print(inspetor.get_table_names())

['clientes', 'empregados']

In [205]:
#lendo uma tabela SQL completa
pd.read_sql_table('empregados', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [206]:
#lendo a tabela porém com colunas específicas
pd.read_sql_table('empregados', engine, columns = ['ID_Cliente', 'Grau_escolaridade', 'Rendimento_anual'])

        ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

In [207]:
#Esta função é essencial para criar e executar expressões SQL literais dentro do seu código Python

from sqlalchemy import text

In [208]:
#Exemplo de execução

query = 'DELETE FROM clientes WHERE ID_Cliente=5008804'
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

In [209]:
query = 'SELECT * FROM clientes'
clientes = pd.read_sql(query, engine)

In [210]:
clientes

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
2,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
3,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [211]:
query = 'DELETE FROM clientes WHERE ID_Cliente = 5008805'

with engine.connect() as conn:
  conn.execute(text(query))
  conn.commit()

In [212]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
1,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
2,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
3,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008811,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438456,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438457,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438458,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438459,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438460,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [213]:
query = 'UPDATE clientes SET Grau_escolaridade = "Ensino superior" where ID_Cliente = 5008808'

In [214]:
with engine.connect() as conn:
  conn.execute(text(query))
  conn.commit()

In [215]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
1,5008808,52,Ensino superior,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
2,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
3,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008811,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438456,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438457,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438458,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438459,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438460,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [216]:
#Desafio: manipulando um banco de dados

#importando bibliotecas, classes, funções
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text

#criando um banco de dados do tipo sqlite, armazenar o banco na memória local
engine = create_engine('sqlite:///:memory:')

#url com a base de dados
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

#criando um dataframe a partir do csv
clientes_banco = pd.read_csv(url)

In [217]:
#conferindo os dados importados
clientes_banco.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [218]:
#criando a tabela clientes_banco
clientes_banco.to_sql('clientes_banco', engine, index = False)

438463

In [219]:
#conferindo a tabela criada
pd.read_sql_table('clientes_banco', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [220]:
#criando as queries
query_1 = 'UPDATE clientes_banco SET Rendimento_anual = 300000 WHERE ID_Cliente = 6840104'
query_2 = 'DELETE FROM clientes_banco WHERE ID_Cliente = 5008809'
query_3 = 'INSERT INTO clientes_banco (ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,\
          Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia) VALUES \
          (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, "Casa/apartamento próprio")'

In [221]:
#conferindo os dados antes de serem alterados
pd.read_sql_query('SELECT * FROM clientes_banco WHERE ID_Cliente = 6840104', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio

In [222]:
#conferindo os dados antes de serem alterados
pd.read_sql_query('SELECT * FROM clientes_banco WHERE ID_Cliente = 5008809', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [223]:
#executando as queries
with engine.connect() as conn:
  conn.execute(text(query_1))
  conn.execute(text(query_2))
  conn.execute(text(query_3))
  conn.commit()

In [224]:
#conferindo os dados depois de serem alterados
pd.read_sql_query('SELECT * FROM clientes_banco WHERE ID_Cliente = 6840104', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio

In [225]:
#conferindo os dados depois de serem alterados
pd.read_sql_query('SELECT * FROM clientes_banco WHERE ID_Cliente = 5008809', engine)

Empty DataFrame
Columns: [ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia]
Index: []

In [226]:
#conferindo os dados depois de serem alterados
pd.read_sql_table('clientes_banco', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio
438462,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio